spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=${SERVER_PORT}

jwt.secret=${JWT_SECRET}
jwt.access-token.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION}

ai.provider=${IA}

# IA - Gemini
ai.gemini.api-key=${GEMINI_API_KEY}
ai.gemini.model=${GEMINI_MODEL}
ai.gemini.max-tokens=${GEMINI_MAX_TOKENS}
ai.gemini.temperature=${GEMINI_TEMPERATURE}
ai.gemini.timeout-seconds=${GEMINI_TIMEOUT_SECONDS}