spring.datasource.url=jdbc:mysql://localhost:3306/tukan_db
spring.datasource.username=root
spring.datasource.password=Lucas_123

server.port=8080

jwt.secret=Tukan2026JwtSecretKeyHmacSHA256Ok
jwt.access-token.expiration=900
jwt.refresh-token.expiration=604800